package com.bottlerocketstudios.continuitysample.legislator.model;

import java.util.List;

/**
 * Automatically generated by jsonGenerator.py
 */
public class LegislatorResponse {
    private static final String TAG = LegislatorResponse.class.getSimpleName();
        
    private long mCount;
    private List<Legislator> mResults;
    private Page mPage;    
    
    public long getCount() {
        return mCount;
    }

    public void setCount(long count) {
        mCount = count;
    }

    public List<Legislator> getResults() {
        return mResults;
    }

    public void setResults(List<Legislator> results) {
        mResults = results;
    }

    public Page getPage() {
        return mPage;
    }

    public void setPage(Page page) {
        mPage = page;
    }

             
}

