package com.bottlerocketstudios.continuitysample.legislator.model;

import android.text.TextUtils;

import java.util.List;

/**
 * Automatically generated by jsonGenerator.py
 */
public class Legislator {
    private static final String TAG = Legislator.class.getSimpleName();

    private boolean mFavorite;

    private String mLastName;
    private String mStateName;
    private String mOffice;
    private String mFax;
    private String mThomasId;
    private String mFirstName;
    private String mMiddleName;
    private long mDistrict;
    private long mSenateClass;
    private boolean mInOffice;
    private String mState;
    private String mTermEnd;
    private String mCrpId;
    private String mOcEmail;
    private String mParty;
    private List<String> mFecIds;
    private long mVotesmartId;
    private String mWebsite;
    private String mLisId;
    private String mGovtrackId;
    private String mFacebookId;
    private long mIcpsrId;
    private String mBioguideId;
    private String mBirthday;
    private String mTermStart;
    private String mNickname;
    private String mContactForm;
    private String mOcdId;
    private String mPhone;
    private String mGender;
    private String mTitle;
    private String mNameSuffix;
    private String mTwitterId;
    private String mChamber;
    private String mStateRank;
    private String mYoutubeId;
    private String mImageUrl;

    public String getLastName() {
        return mLastName;
    }

    public void setLastName(String lastName) {
        mLastName = lastName;
    }

    public String getStateName() {
        return mStateName;
    }

    public void setStateName(String stateName) {
        mStateName = stateName;
    }

    public String getOffice() {
        return mOffice;
    }

    public void setOffice(String office) {
        mOffice = office;
    }

    public String getFax() {
        return mFax;
    }

    public void setFax(String fax) {
        mFax = fax;
    }

    public String getThomasId() {
        return mThomasId;
    }

    public void setThomasId(String thomasId) {
        mThomasId = thomasId;
    }

    public String getFirstName() {
        return mFirstName;
    }

    public void setFirstName(String firstName) {
        mFirstName = firstName;
    }

    public String getMiddleName() {
        return mMiddleName;
    }

    public void setMiddleName(String middleName) {
        mMiddleName = middleName;
    }

    public long getDistrict() {
        return mDistrict;
    }

    public void setDistrict(long district) {
        mDistrict = district;
    }

    public long getSenateClass() {
        return mSenateClass;
    }

    public void setSenateClass(long senateClass) {
        mSenateClass = senateClass;
    }

    public boolean isInOffice() {
        return mInOffice;
    }

    public void setInOffice(boolean inOffice) {
        mInOffice = inOffice;
    }

    public String getState() {
        return mState;
    }

    public void setState(String state) {
        mState = state;
    }

    public String getTermEnd() {
        return mTermEnd;
    }

    public void setTermEnd(String termEnd) {
        mTermEnd = termEnd;
    }

    public String getCrpId() {
        return mCrpId;
    }

    public void setCrpId(String crpId) {
        mCrpId = crpId;
    }

    public String getOcEmail() {
        return mOcEmail;
    }

    public void setOcEmail(String ocEmail) {
        mOcEmail = ocEmail;
    }

    public String getParty() {
        return mParty;
    }

    public void setParty(String party) {
        mParty = party;
    }

    public List<String> getFecIds() {
        return mFecIds;
    }

    public void setFecIds(List<String> fecIds) {
        mFecIds = fecIds;
    }

    public long getVotesmartId() {
        return mVotesmartId;
    }

    public void setVotesmartId(long votesmartId) {
        mVotesmartId = votesmartId;
    }

    public String getWebsite() {
        return mWebsite;
    }

    public void setWebsite(String website) {
        mWebsite = website;
    }

    public String getLisId() {
        return mLisId;
    }

    public void setLisId(String lisId) {
        mLisId = lisId;
    }

    public String getGovtrackId() {
        return mGovtrackId;
    }

    public void setGovtrackId(String govtrackId) {
        mGovtrackId = govtrackId;
    }

    public String getFacebookId() {
        return mFacebookId;
    }

    public void setFacebookId(String facebookId) {
        mFacebookId = facebookId;
    }

    public long getIcpsrId() {
        return mIcpsrId;
    }

    public void setIcpsrId(long icpsrId) {
        mIcpsrId = icpsrId;
    }

    public String getBioguideId() {
        return mBioguideId;
    }

    public void setBioguideId(String bioguideId) {
        mBioguideId = bioguideId;
    }

    public String getBirthday() {
        return mBirthday;
    }

    public void setBirthday(String birthday) {
        mBirthday = birthday;
    }

    public String getTermStart() {
        return mTermStart;
    }

    public void setTermStart(String termStart) {
        mTermStart = termStart;
    }

    public String getNickname() {
        return mNickname;
    }

    public void setNickname(String nickname) {
        mNickname = nickname;
    }

    public String getContactForm() {
        return mContactForm;
    }

    public void setContactForm(String contactForm) {
        mContactForm = contactForm;
    }

    public String getOcdId() {
        return mOcdId;
    }

    public void setOcdId(String ocdId) {
        mOcdId = ocdId;
    }

    public String getPhone() {
        return mPhone;
    }

    public void setPhone(String phone) {
        mPhone = phone;
    }

    public String getGender() {
        return mGender;
    }

    public void setGender(String gender) {
        mGender = gender;
    }

    public String getTitle() {
        return mTitle;
    }

    public void setTitle(String title) {
        mTitle = title;
    }

    public String getNameSuffix() {
        return mNameSuffix;
    }

    public void setNameSuffix(String nameSuffix) {
        mNameSuffix = nameSuffix;
    }

    public String getTwitterId() {
        return mTwitterId;
    }

    public void setTwitterId(String twitterId) {
        mTwitterId = twitterId;
    }

    public String getChamber() {
        return mChamber;
    }

    public void setChamber(String chamber) {
        mChamber = chamber;
    }

    public String getStateRank() {
        return mStateRank;
    }

    public void setStateRank(String stateRank) {
        mStateRank = stateRank;
    }

    public String getYoutubeId() {
        return mYoutubeId;
    }

    public void setYoutubeId(String youtubeId) {
        mYoutubeId = youtubeId;
    }


    @Override
    public boolean equals(Object obj) {
        if (obj instanceof Legislator) {
            return TextUtils.equals(((Legislator) obj).getBioguideId(), getBioguideId());
        }
        return super.equals(obj);
    }

    @Override
    public int hashCode() {
        return getBioguideId().hashCode();
    }

    public boolean isFavorite() {
        return mFavorite;
    }

    public void setFavorite(boolean favorite) {
        mFavorite = favorite;
    }

    public void setImageUrl(String imageUrl) {
        mImageUrl = imageUrl;
    }

    public String getImageUrl() {
        return mImageUrl;
    }
}

