package com.bottlerocketstudios.continuitysample.legislator.model;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.List;

/**
 * Automatically generated by jsonGenerator.py
 */
public class Page {
    private static final String TAG = Page.class.getSimpleName();
        
    private long mCount;
    private long mPerPage;
    private long mPage;    
    
    public long getCount() {
        return mCount;
    }

    public void setCount(long count) {
        mCount = count;
    }

    public long getPerPage() {
        return mPerPage;
    }

    public void setPerPage(long perPage) {
        mPerPage = perPage;
    }

    public long getPage() {
        return mPage;
    }

    public void setPage(long page) {
        mPage = page;
    }

             
}

